### ISSUE TITLE
Issue communicating with ROS node on WSL2

### ISSUE THREAD

**Issue by rallamraju1** [ColorsWind/WSL-Port-Forwarding#1]
I noticed that you were testing with ROS in your readme and that's why I am posting here. 

I am setting up a simulation with ROS nodes distributed across three machines and I need one machine to run rviz.  I have one windows machine running WSL2 and two other windows machines running WSL1.  On the WSL2 machine, I run the port forwarding script and start roscore with the ROS_MASTER_URI and ROS_IP set to the IP address of the virtual machine. On the other two windows machines running WSL1, I set the ROS_MASTER_URI as the IP address of the host computer running WSL2.

For testing I am using a simple listener-talker example and when I launch a talker node on WSL1,  I am able to subscribe and read the messages on listener node running on WSL2. But when I do the opposite and run talker node on WSL2 and subscribe to the topic on WSL1, I am unable to read the messages.

I am not sure how to debug this issue as I don't know if the problem is with port forwarding or with ROS data transport mechanism.

**Comment by ColorsWind** [comment]
First, you should set ROS_MASTER_URI and ROS_IP to your host IP on your WSL2 machine.

According to [ROS wiki](http://wiki.ros.org/ROS/NetworkSetup), ROS requires 

> bi-directional connectivity between all pairs of machines, on all ports, 

not just the master. If you try to monitor your WSL1 machine, you may find even when you just subscribe and read the messages, ROS will attempt to accept active connections. So, you have to make sure the master node can access the “slave node “.

I am not sure about WSL1 network, but you should also run the port forwarding script on the “slave node” machine if their ROS runs on WSL2.

**Comment by rallamraju1** [comment]
Thank you so much! It worked when I set ROS_MASTER_URI and ROS_IP to IP address of the host instead of the IP address of the virtual machine. The rosmaster throws a warning though that the IP address do not match, but I think I can ignore this.
