### ISSUE TITLE
Program names with slashes in them break

### ISSUE THREAD

**Issue by jed2nd** [ColorsWind/WSL-Port-Forwarding#2]
If the running program has a slash in the name (i.e. `/venv/bin/python3 blah.py`), the program throws an exception at line 66.  Simple fix is as follows:

replace:
```
pid, program_name = items[PID_PROGRAM].split("/")
```

With:
```
pid = items[PID_PROGRAM].split("/")[0]
program_name = "/".join(items[PID_PROGRAM].split("/")[1:])
```

**Comment by ColorsWind** [comment]
Hello jed2nd, thank you for your feedback. I have fixed this problem. You can get new scripts through pip or from this repository. However, since I have no program with a slash in the name here, it has not been fully tested, but it should work properly.
